-- Databricks notebook source
desc extended 
cdspocchange.ctrep_bcont__ct

-- COMMAND ----------

select count(*) from cdspocchange.ctrep_bcont__ct

-- COMMAND ----------

create view cdspocchange.BCONT_V AS
SELECT        MANDT AS CLIENT, BPCONTACT AS BP_CONTACT, PCATEGORY AS PARTNER_TYPE, PARTNER AS BUSINESSPARTNER, ALTPARTNER AS CONTACT_PERSON, RLTYP AS OBJECT_PART, 
CTYPE AS TYPE, CCLASS AS CLASS, ACTIVITY AS ACTION, F_COMING AS IN_OR_OUTGOING, ORIGIN, CTDATE AS DATE1, CTTIME AS TIME1, ERDAT AS CREATED_ON, ERNAM AS CREATED_BY, 
AEDAT AS CHANGED_ON, AENAM AS CHANGED_BY,BEGRU AS AUTHORIZGROUP, LOEVM AS DELETE1, WFID AS WORKFLOW, ADDINFO AS ADD_INFO, PRIORITY, CUSTINFO AS CUSTOMER_INFO, 
SPARTE AS DIVISION, BUKRS AS COMPANY_CODE, ZZSOURCE AS SOURCE_SYSTEM, ZZCTI_RECORD AS CTI_RECORD, ZZFEEDBACK AS DTE_CARES_FEEDBACK, ZZLTYPE_DESC AS LETTER_TYPE_DESCRIPT, ZZMEDVAL AS MEDIUM_VALUE  FROM    cdspoc.BCONT

-- COMMAND ----------

select count(*) from cdspoc.BCONT
union all
select count(*) from cdspocchange.ctrep_bcont

-- COMMAND ----------

select count(*) from cdspocchange.BCONT_V
union all 
select count(*) from cdspoc.BCONT

-- COMMAND ----------

describe extended cdspocchange.ctrep_bcont

-- COMMAND ----------

describe cdspocchange.BCONT_V

-- COMMAND ----------

select CLIENT	,
 BP_CONTACT	,
 PARTNER_TYPE	,
 BUSINESSPARTNER	,
 CONTACT_PERSON	,
 OBJECT_PART	,
 TYPE	,
 CLASS	,
 ACTION	,
 IN_OR_OUTGOING	,
 ORIGIN	,
 DATE1	,
 TIME1	,
 CREATED_ON	,
 CREATED_BY	,
 CHANGED_ON	,
 CHANGED_BY	,
 AUTHORIZGROUP	,
 DELETE1	,
 WORKFLOW	,
 ADD_INFO	,
 PRIORITY	,
 CUSTOMER_INFO	,
 DIVISION	,
 COMPANY_CODE	,
 SOURCE_SYSTEM	,
 CTI_RECORD	,
 DTE_CARES_FEEDBACK	,
 LETTER_TYPE_DESCRIPT	,
 MEDIUM_VALUE	
 from cdspocchange.BCONT_V
minus 
select MANDT
,	BPCONTACT
,	PCATEGORY
,	PARTNER
,	ALTPARTNER
,	RLTYP
,	CTYPE
,	CCLASS
,	ACTIVITY
,	F_COMING
,	ORIGIN
,	CTDATE
,	CTTIME
,	ERDAT
,	ERNAM
,	AEDAT
,	AENAM
,	BEGRU
,	LOEVM
,	WFID
,	ADDINFO
,	PRIORITY
,	CUSTINFO
,	SPARTE
,	BUKRS
,	ZZSOURCE
,	ZZCTI_RECORD
,	ZZFEEDBACK
,	ZZLTYPE_DESC
,	ZZMEDVAL 
 from cdspocchange.ctrep_bcont

-- COMMAND ----------

-- CREATE VIEW cdspocchange.BCONT_V (CLIENT, BP_CONTACT, PARTNER_TYPE, BUSINESSPARTNER, CONTACT_PERSON, OBJECT_PART, TYPE, CLASS, ACTION, IN_OR_OUTGOING, ORIGIN, DATE1, TIME1, 
-- CREATED_ON, CREATED_BY, CHANGED_ON, CHANGED_BY, AUTHORIZGROUP, DELETE1, WORKFLOW, ADD_INFO, PRIORITY, CUSTOMER_INFO, DIVISION, COMPANY_CODE, SOURCE_SYSTEM, CTI_RECORD, 
-- DTE_CARES_FEEDBACK, LETTER_TYPE_DESCRIPT, MEDIUM_VALUE ) AS SELECT 
-- MANDT,BPCONTACT,PCATEGORY,PARTNER,ALTPARTNER,RLTYP,CTYPE,CCLASS,ACTIVITY,F_COMING,ORIGIN,CTDATE,CTTIME,ERDAT,ERNAM,AEDAT,AENAM,BEGRU,LOEVM,WFID,ADDINFO,PRIORITY,CUSTINFO,
-- SPARTE,BUKRS,ZZSOURCE,ZZCTI_RECORD,ZZFEEDBACK,ZZLTYPE_DESC,ZZMEDVAL FROM cdspocchange.ctrep_bcont