// Databricks notebook source
// DBTITLE 1,creation of  : CRMD_DHR_ACTIV_v
spark.sql(""" create or replace temporary view CRMD_DHR_ACTIV_v as select GUID as OBJECT_GUID,
CHANGED_AT as CHANGED_ON,
CATEGORY as CATEGORY,
PERSON_RESP as EMPLOYEE_RESP,
PRIORITY as PRIORITY,
DESCRIPTION_UC as DESCRIPTION,
ACTIVITY_PARTNER as ACTIVITYPARTNER,
PROCESS_TYPE as TRANSACTION_TYPE,
CONTACT_PERSON as CONTACT_PERS,
DIRECTION as DIRECTION,
FROMDATE as START_DATE,
TODATE as END_DATE,
STAT_OPEN as OPEN,
STATUS as STATUS,
USER_STAT_PROC as STATUS_PROFILE,
ACT_TOT_DURA as DURATION_VALUE,
ACT_TOT_UNIT as TIME_UNIT
from cdspocchange.CRMD_DHR_ACTIV """)

// COMMAND ----------

// DBTITLE 1,creation of CRMD_ORDERADM_H_v
spark.sql(""" create or replace temporary view CRMD_ORDERADM_H_v as select GUID as OBJECT_GUID,
OBJECT_ID as TRANSACTION_NO,
PROCESS_TYPE as TRANSACTION_TYPE,
POSTING_DATE as POSTING_DATE,
DESCRIPTION as DESCRIPTION,
DESCR_LANGUAGE as DESCR_LANGUAGE,
CREATED_AT as CREATED_AT,
CREATED_BY as CREATED_BY,
CHANGED_AT as CHANGED_AT,
CHANGED_BY as CHANGED_BY,
HEAD_CHANGED_AT as CHANGED_ON,
OBJECT_TYPE as TRANS_CAT,
ARCHIVING_FLAG as CAN_BE_ARCHIVED,
DESCRIPTION_UC as DESCRIPTION_UC,
OBJECT_ID_OK as NUMBER_VALID,
CRM_CHANGED_AT as CRM_CHANGED_ON
from cdspocchange.CRMD_ORDERADM_H """)

// COMMAND ----------

// DBTITLE 1,creation of CRMD_ACTIVITY_H_v
spark.sql(""" create or replace temporary view CRMD_ACTIVITY_H_v as select GUID as OBJECT_GUID,
CATEGORY as CATEGORY,
DIRECTION as DIRECTION,
EXTERN_ACT_ID as EXTERNAL_NO,
ADDRESS_ID as ACTIVITY_ADDRESS,
COMPLETION as percent_COMPLETE,
ACTIVITY_H_DUMMY as DUMMY,
ZZAFLD000013 as CLASS,
ZZAFLD000014 as ACTION,
ZZAFLD000015 as SOURCE_SYSTEM,
ZZCOMEMPHTXT as COMMUNICATION_MEDIU,
ZZBFLD00000H as BUSINESS_AGREEMENT,
ZZBFLD00000I as DEFECT_DESCRIPTION,
ZZESCALATION as ZZESCALATION,
TASK as TASK,
CLASS as ACTIVITY_CLASS
from cdspocchange.CRMD_ACTIVITY_H """)

// COMMAND ----------

// DBTITLE 1,Join 3
// MAGIC %sql
// MAGIC CREATE OR REPLACE TEMPORARY VIEW CRM_V1 AS
// MAGIC select CRMD_DHR_ACTIV_V.OBJECT_GUID,
// MAGIC CRMD_DHR_ACTIV_V.CHANGED_ON,
// MAGIC CRMD_DHR_ACTIV_V.CATEGORY,
// MAGIC CRMD_DHR_ACTIV_V.EMPLOYEE_RESP,
// MAGIC CRMD_DHR_ACTIV_V.PRIORITY,
// MAGIC CRMD_DHR_ACTIV_V.DESCRIPTION,
// MAGIC CRMD_DHR_ACTIV_V.ACTIVITYPARTNER,
// MAGIC CRMD_DHR_ACTIV_V.TRANSACTION_TYPE,
// MAGIC CRMD_DHR_ACTIV_V.CONTACT_PERS,
// MAGIC CRMD_DHR_ACTIV_V.DIRECTION,
// MAGIC CRMD_DHR_ACTIV_V.START_DATE,
// MAGIC CRMD_DHR_ACTIV_V.END_DATE,
// MAGIC CRMD_DHR_ACTIV_V.OPEN,
// MAGIC CRMD_DHR_ACTIV_V.STATUS,
// MAGIC CRMD_DHR_ACTIV_V.STATUS_PROFILE,
// MAGIC CRMD_DHR_ACTIV_V.DURATION_VALUE,
// MAGIC CRMD_DHR_ACTIV_V.TIME_UNIT,
// MAGIC
// MAGIC CRMD_ORDERADM_H_V.TRANSACTION_NO,
// MAGIC CRMD_ORDERADM_H_V.POSTING_DATE,
// MAGIC CRMD_ORDERADM_H_V.DESCRIPTION_UC
// MAGIC CRMD_ORDERADM_H_V.DESCR_LANGUAGE,
// MAGIC CRMD_ORDERADM_H_V.CREATED_AT,
// MAGIC CRMD_ORDERADM_H_V.CREATED_BY,
// MAGIC CRMD_ORDERADM_H_V.CHANGED_AT,
// MAGIC CRMD_ORDERADM_H_V.CHANGED_BY,
// MAGIC CRMD_ORDERADM_H_V.CHANGED_ON,
// MAGIC CRMD_ORDERADM_H_V.TRANS_CAT,
// MAGIC CRMD_ORDERADM_H_V.CAN_BE_ARCHIVED,
// MAGIC CRMD_ORDERADM_H_V.NUMBER_VALID,
// MAGIC CRMD_ORDERADM_H_V.CRM_CHANGED_ON,
// MAGIC
// MAGIC CRMD_ACTIVITY_H_V.CATEGORY,
// MAGIC CRMD_ACTIVITY_H_V.DIRECTION,
// MAGIC CRMD_ACTIVITY_H_V.EXTERNAL_NO,
// MAGIC CRMD_ACTIVITY_H_V.%_COMPLETE,
// MAGIC CRMD_ACTIVITY_H_V.CLASS,
// MAGIC CRMD_ACTIVITY_H_V.ACTION,
// MAGIC CRMD_ACTIVITY_H_V.COMMUNICATION_MEDIU,
// MAGIC CRMD_ACTIVITY_H_V.BUSINESS_AGREEMENT,
// MAGIC CRMD_ACTIVITY_H_V.DEFECT_DESCRIPTION,
// MAGIC CRMD_ACTIVITY_H_V.ZZESCALATION,
// MAGIC CRMD_ACTIVITY_H_V.TASK,
// MAGIC CRMD_ACTIVITY_H_V.ACTIVITY_CLASS,
// MAGIC CRMD_ACTIVITY_H_V.ACTIVITY_ADDRESS,
// MAGIC CRMD_ACTIVITY_H_V.SOURCE_SYSTEM
// MAGIC
// MAGIC CRM_ACTIVITY_TEXT.CLASS_TXT,
// MAGIC CRM_ACTIVITY_TEXT.ACTION_TXT
// MAGIC
// MAGIC from CRMD_DHR_ACTIV_V left join CRMD_ORDERADM_H_V on CRMD_DHR_ACTIV_V.OBJECT_GUID = CRMD_ORDERADM_H_V.OBJECT_GUID
// MAGIC left join CRMD_ACTIVITY_H_V on CRMD_DHR_ACTIV_V.OBJECT_GUID = CRMD_ACTIVITY_H_V.OBJECT_GUID
// MAGIC left join CRM_ACTIVITY_TEXT 
// MAGIC on CRMD_ACTIVITY_H_V.CLASS = CRM_ACTIVITY_TEXT.CCLASS and CRMD_ACTIVITY_H_V.ACTION = CRM_ACTIVITY_TEXT.ACTIVITY

// COMMAND ----------

// DBTITLE 1,join 4
// MAGIC %sql
// MAGIC CREATE OR REPLACE TEMPORARY VIEW CRM_V2 AS
// MAGIC SELECT v1.*, 
// MAGIC CRM_ACTIVITY_TEXT.CLASS_TXT AS CLASS_TXT_1 from CRM_V1  v1 left join CRM_ACTIVITY_TEXT
// MAGIC ON v1.CLASS = CRM_ACTIVITY_TEXT.CCLASS

// COMMAND ----------

// DBTITLE 1,Aggregation
// MAGIC %sql
// MAGIC CREATE OR REPLACE TEMPORARY VIEW CRM_V3 AS 
// MAGIC select 
// MAGIC ACTIVITY_CLASS,
// MAGIC ZZESCALATION,
// MAGIC DEFECT_DESCRIPTION,
// MAGIC BUSINESS_AGREEMENT,
// MAGIC ACTION,
// MAGIC CLASS,
// MAGIC %_COMPLETE,
// MAGIC ACTIVITY_ADDRESS,
// MAGIC EXTERNAL_NO,
// MAGIC CRM_CHANGED_ON,
// MAGIC CHANGED_ON as ORD_CHANGED_ON,
// MAGIC CHANGED_AT,
// MAGIC CREATED_AT,
// MAGIC CHANGED_ON,
// MAGIC NUMBER_VALID,
// MAGIC CAN_BE_ARCHIVED,
// MAGIC TRANS_CAT,
// MAGIC CHANGED_BY,
// MAGIC CREATED_BY,
// MAGIC DESCR_LANGUAGE,
// MAGIC POSTING_DATE,
// MAGIC TRANSACTION_NO,
// MAGIC TIME_UNIT,
// MAGIC sum(DURATION_VALUE) as DURATION_VALUE,
// MAGIC STATUS_PROFILE,
// MAGIC STATUS,
// MAGIC OPEN,
// MAGIC END_DATE,
// MAGIC START_DATE,
// MAGIC DIRECTION,
// MAGIC CONTACT_PERS,
// MAGIC TRANSACTION_TYPE,
// MAGIC ACTIVITYPARTNER,
// MAGIC DESCRIPTION,
// MAGIC PRIORITY,
// MAGIC EMPLOYEE_RESP,
// MAGIC CATEGORY,
// MAGIC OBJECT_GUID,
// MAGIC CATEGORY AS ACTIVITY_CATEGORY,
// MAGIC DIRECTION AS ACTIVITY_DIRECTION,
// MAGIC COMMUNICATION_MEDIU,
// MAGIC TASK,
// MAGIC CLASS_TXT,
// MAGIC ACTION_TXT,
// MAGIC CLASS_TXT,
// MAGIC CLASS_TXT_1,
// MAGIC SOURCE_SYSTEM, 
// MAGIC count(OBJECT_GUID) as Interactions
// MAGIC from CRM_V2
// MAGIC group by
// MAGIC ACTIVITY_CLASS,
// MAGIC ZZESCALATION,
// MAGIC DEFECT_DESCRIPTION,
// MAGIC BUSINESS_AGREEMENT,
// MAGIC ACTION,
// MAGIC CLASS,
// MAGIC %_COMPLETE,
// MAGIC ACTIVITY_ADDRESS,
// MAGIC EXTERNAL_NO,
// MAGIC CRM_CHANGED_ON,
// MAGIC CHANGED_ON ,
// MAGIC CHANGED_AT,
// MAGIC CREATED_AT,
// MAGIC CHANGED_ON,
// MAGIC NUMBER_VALID,
// MAGIC CAN_BE_ARCHIVED,
// MAGIC TRANS_CAT,
// MAGIC CHANGED_BY,
// MAGIC CREATED_BY,
// MAGIC DESCR_LANGUAGE,
// MAGIC POSTING_DATE,
// MAGIC TRANSACTION_NO,
// MAGIC TIME_UNIT,
// MAGIC STATUS_PROFILE,
// MAGIC STATUS,
// MAGIC OPEN,
// MAGIC END_DATE,
// MAGIC START_DATE,
// MAGIC DIRECTION,
// MAGIC CONTACT_PERS,
// MAGIC TRANSACTION_TYPE,
// MAGIC ACTIVITYPARTNER,
// MAGIC DESCRIPTION,
// MAGIC PRIORITY,
// MAGIC EMPLOYEE_RESP,
// MAGIC CATEGORY,
// MAGIC OBJECT_GUID,
// MAGIC CATEGORY ,
// MAGIC DIRECTION ,
// MAGIC COMMUNICATION_MEDIU,
// MAGIC TASK,
// MAGIC CLASS_TXT,
// MAGIC ACTION_TXT,
// MAGIC CLASS_TXT,
// MAGIC CLASS_TXT_1
// MAGIC SOURCE_SYSTEM 

// COMMAND ----------

// MAGIC %sql
// MAGIC CREATE OR REPLACE VIEW CRM_V4 AS 
// MAGIC select CRM_V3.*, 
// MAGIC if(DIRECTION = '0', 'INBOUND', if (DIRECTION = '1', 'OUTBOUND', '')) as DIRECTION_TXT
// MAGIC ,to_date(CHANGED_ON) as DATE_INTR
// MAGIC ,sum(CHANGED_ON)  as CHANGED_ON_DHR   ---?
// MAGIC ,localtoutc(utcnow(),'EST') as  CURR_TSTMP   ------current timestamp
// MAGIC ,now() as CURR_DT   --------current date
// MAGIC ,daysbetween(DATE_INTR,CURR_DT) as DIFF_DT
// MAGIC ,leftstr(string("CHANGED_ON"), 4) as YEAR_INTR
// MAGIC from CRM_V3

// COMMAND ----------

