// Databricks notebook source
// MAGIC %sql
// MAGIC
// MAGIC select * from (
// MAGIC SELECT ORDER, CREATED_ON, CHANGED_ON, CREATED, RELEASED, COMPLETED, CLOSED, TIME_CREATED, CHANGED_AT, MOVE_IN_DOC, MOVE_OUT_DOC,
// MAGIC CASE WHEN (MOVE_IN_DOC <> "" AND MOVE_OUT_DOC <> "") THEN MOVE_IN_DOC
// MAGIC WHEN (MOVE_IN_DOC = "" AND MOVE_OUT_DOC = "")THEN ""
// MAGIC WHEN (MOVE_IN_DOC = "") THEN MOVE_OUT_DOC
// MAGIC WHEN (MOVE_OUT_DOC = "") THEN MOVE_IN_DOC AS ORDER_MIMO_DOC
// MAGIC ,IF(CHANGED_ON = "00000000", (CREATED_ON + TIME_CREATED), (CHANGED_ON + CHANGED_AT)) AS TIMESTAMP
// MAGIC from AUFK_V) where ORDER_MIMO_DOC <> ""

// COMMAND ----------

// MAGIC %sql
// MAGIC CREATE OR REPLACE TEMPORARY VIEW AGG AS
// MAGIC select p1.ORDER_MIMO_DOC, p1.TIMESTAMP, p2.ORDER from PROJ_1 p1 inner join PROJ_1 P2
// MAGIC ON p1.ORDER_MIMO_DOC =  p2.ORDER_MIMO_DOC and p1.TIMESTAMP  = p2.TIMESTAMP

// COMMAND ----------

// MAGIC %sql
// MAGIC CREATE OR REPLACE TEMPORARY VIEW SEM AS
// MAGIC select count(ORDER_MIMO_DOC), ORDER_MIMO_DOC, ORDER,TIMESTAMP from AGG GROUP BY ORDER,TIMESTAMP