-- Databricks notebook source
CREATE OR REPLACE TEMP VIEW UNION_DATA AS 
select * 
,if(moveinDt < MICreatedOn, "Retro", "") as  RetroMI
,days_between(moveinDt, MICreatedOn) as MIDaysDiff
,leftstr(BEZUGSDAT, 4)
from(
select EINZBELEG
,VKONT
,KUNDE
,BEZUGSDAT
,STORNOKZ
,ADDADR
,ERDAT
,ERNAM
,AEDAT
,AENAM
,LOEVM
,date(BEZUGSDAT) as MoveinDt
,date(ERDAT) as MICreatedOn
,date(AEDAT) as MIChangedOn
,IF(MoveinDt < MICreatedOn , "RETRO" , "") AS RetroMI
,DAYS_BETWEEN(MoveinDt , MICreatedOn) AS MIDaysDiff
,leftstr(BEZUGSDAT, 4) as YEAR
FROM EEIN
UNION ALL
SELECT 
AUSZBELEG
,KUNDE
,VKONT
,DEPARTUREDATE
,STORAUSZ
,ERDAT
,AEDAT
,ERNAM
,AENAM
,LOEVM
,GPVKCHDATE
,STORAUSZ
,ERDAT
,AEDAT
,ERNAM
,AENAM
,LOEVM
,GPVKCHDATE
,DATE(DEPARTUREDATE) AS MOVEOUTDT
,date(ERDAT) AS MOCreatedOn
,DATE(AEDAT) AS MOChangedOn
,IF(MOVEOUTDT < MOCreatedOn , "RETRO" , "") AS RetroMo
,DAYS_BETWEEN(MOVEOUTDT , MOCreatedOn) AS MODaysDiff
,leftstr(DEPARTUREDATE, 4) as YEAR
FROM EAUS

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW FINAL_VIEW AS 
SELECT *, (if VKNOT!= " ", 1, 0) AS COUNT_1
FROM UNION_DATA